import pandas as pd
from pandas.io import sql


map_limits_dict = {'receiver': {
                          'BR': {'Company': {'C&P': {'EMV': 15000, 'MAGSTRIPE': 1500}, 
                                             'C&S': {'EMV': 5000, 'MAGSTRIPE': 1500}}, 
                                  'Person': {'C&P': {'EMV': 3000, 'MAGSTRIPE': 500}, 
                                             'C&S': {'EMV': 3000, 'MAGSTRIPE': 500}}},
                          'MX': {'Company': {'C&P': {'EMV': 5000000, 'MAGSTRIPE': 5000000}, 
                                             'C&S': {'EMV': 5000000, 'MAGSTRIPE': 5000000}}, 
                                  'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 10000}, 
                                             'C&S': {'EMV': 10000, 'MAGSTRIPE': 10000}}},
                          'DK': {'Company': {'C&P': {'EMV': 5000000, 'MAGSTRIPE': 2000000}, 
                                             'C&S': {'EMV': 2000000, 'MAGSTRIPE': 2000000}}, 
                                  'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                             'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}},
                          'FI': {'Company': {'C&P': {'EMV': 5000000, 'MAGSTRIPE': 2000000}, 
                                             'C&S': {'EMV': 2000000, 'MAGSTRIPE': 2000000}}, 
                                  'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                             'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}},
                          'DE': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}, 
                                  'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                             'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}},
                          'FR': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}},
                          'IT': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}},
                          'NL': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}},
                          'NO': {'Company': {'C&P': {'EMV': 5000000, 'MAGSTRIPE': 2000000}, 
                                             'C&S': {'EMV': 2000000, 'MAGSTRIPE': 2000000}}, 
                                  'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                             'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}},
                          'ES': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}, 
                                  'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                             'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}},
                          'SE': {'Company': {'C&P': {'EMV': 5000000, 'MAGSTRIPE': 2000000}, 
                                             'C&S': {'EMV': 2000000, 'MAGSTRIPE': 2000000}}, 
                                  'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                             'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}},
                          'GB': {'Company': {'C&P': {'EMV': 500000, 'MAGSTRIPE': 200000}, 
                                             'C&S': {'EMV': 200000, 'MAGSTRIPE': 200000}}, 
                                  'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                             'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}}
                          }, 
              
              'sender': {'BR': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 1500}, 
                                            'C&S': {'EMV': 3000, 'MAGSTRIPE': 1500}}, 
                                'Person': {'C&P': {'EMV': 2000, 'MAGSTRIPE': 250}, 
                                           'C&S': {'EMV': 2000, 'MAGSTRIPE': 250}}}, 
                         'MX': {'Company': {'C&P': {'EMV': 25000, 'MAGSTRIPE': 25000}, 
                                            'C&S': {'EMV': 25000, 'MAGSTRIPE': 25000}}, 
                                'Person': {'C&P': {'EMV': 3000, 'MAGSTRIPE': 3000}, 
                                           'C&S': {'EMV': 3000, 'MAGSTRIPE': 3000}}}, 
                         'DK': {'Company': {'C&P': {'EMV': 50000, 'MAGSTRIPE': 25000}, 
                                            'C&S': {'EMV': 25000, 'MAGSTRIPE': 25000}}, 
                                'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                           'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}}, 
                         'FI': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}, 
                                'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                           'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}}, 
                         'DE': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}, 
                                'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                           'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}}, 
                         'FR': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}}, 
                         'IT': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}}, 
                         'NL': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}}, 
                         'NO': {'Company': {'C&P': {'EMV': 50000, 'MAGSTRIPE': 25000}, 
                                            'C&S': {'EMV': 25000, 'MAGSTRIPE': 25000}}, 
                                'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                           'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}}, 
                         'ES': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}, 
                                'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                           'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}}, 
                         'SE': {'Company': {'C&P': {'EMV': 50000, 'MAGSTRIPE': 25000}, 
                                            'C&S': {'EMV': 25000, 'MAGSTRIPE': 25000}}, 
                                'Person': {'C&P': {'EMV': 10000, 'MAGSTRIPE': 1000}, 
                                           'C&S': {'EMV': 10000, 'MAGSTRIPE': 1000}}}, 
                         'GB': {'Company': {'C&P': {'EMV': 5000, 'MAGSTRIPE': 2500}, 
                                            'C&S': {'EMV': 2500, 'MAGSTRIPE': 2500}}, 
                                'Person': {'C&P': {'EMV': 1000, 'MAGSTRIPE': 100}, 
                                           'C&S': {'EMV': 1000, 'MAGSTRIPE': 100}}}
                        }
              }


#df['limit_receiver'] = df.apply(lambda row: map_limits['receiver'][row.country_id][row.legal_entity_type]
#                                [row.reader_limit][row.cardPaymentEntryMode], axis=1)
#df['limit_sender'] = df.apply(lambda row: map_limits['sender'][row.country_id][row.legal_entity_type]
#                              [row.reader_limit][row.cardPaymentEntryMode], axis=1)